In [371]:

import numpy as np
import matplotlib.pyplot as plt 
import torch
from torch import nn
import random

from torch.nn import functional as F


In [372]:

data =  torch.tensor( random.sample(range(1, 500), 100) )

device = "cpu"

batch_size = 4
block_size = 16


def get_batch():

        
    ix = torch.randint(   len(data) - block_size, (batch_size,)   )
    
    x  = torch.stack(    [  data[   i : i+block_size ]     for i in ix ]    ) 
    y  = torch.stack(    [  data[ i+1 : i+1+block_size ]   for i in ix ]    )
    
    x, y = x.to(device), y.to(device)

    return x, y

get_batch()

##### or

temp_batch_size = 4
temp_block_size = 16

## select random starting points for the 4 sentences
ix = torch.randint(   
            len(data) - temp_block_size, 
            (temp_batch_size,)   
)

print( ix )


for index_temp in ix:
    print(  data[index_temp]  )



x  = torch.stack(    
    [ data[   i : i+  temp_block_size ]   for i in ix ] 
    
) 

y  = torch.stack(    
    [ data[ i+1 : i+1+ temp_block_size ]  for i in ix ]    
)

print(x)
print(y)



tensor([18, 34, 26, 74])
tensor(291)
tensor(182)
tensor(484)
tensor(473)
tensor([[291, 206, 234,  20, 440,  34, 328, 189, 484, 154, 365, 211, 445, 357,
         267, 235],
        [182, 275,  74, 331, 270,   7, 482, 254, 317,  48, 469, 255, 360, 324,
         334,  49],
        [484, 154, 365, 211, 445, 357, 267, 235, 182, 275,  74, 331, 270,   7,
         482, 254],
        [473, 200, 196, 401, 141, 286, 386, 133,  33, 353, 188, 329, 263, 441,
          51, 259]])
tensor([[206, 234,  20, 440,  34, 328, 189, 484, 154, 365, 211, 445, 357, 267,
         235, 182],
        [275,  74, 331, 270,   7, 482, 254, 317,  48, 469, 255, 360, 324, 334,
          49, 337],
        [154, 365, 211, 445, 357, 267, 235, 182, 275,  74, 331, 270,   7, 482,
         254, 317],
        [200, 196, 401, 141, 286, 386, 133,  33, 353, 188, 329, 263, 441,  51,
         259, 260]])
