In [5]:

from PIL import Image

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [48]:

import numpy as np
import matplotlib.pyplot as plt 
import torch
from torch import nn

from torch.nn import functional as F


In [6]:

a = np.array(   [4,5,2,6,8]    ) 
print(a)


[4 5 2 6 8]


In [8]:

list_of_lists = [[1, 2, 3, 4], 
                 [5, 6, 7, 8] ,
                 [9, 10, 11, 12]]

b = np.array(list_of_lists) 

print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:

X = b[:, :3]

X


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [14]:

X.shape


(3, 3)

In [17]:

y = b[:, 3]

y


array([ 4,  8, 12])


## Problem 34


In [22]:

a_tr = torch.ones(5)
print( a_tr )


tensor([1., 1., 1., 1., 1.])


In [23]:

a_tr[2]  =  1456.0


In [24]:

print(  a_tr  )


tensor([1.0000e+00, 1.0000e+00, 1.4560e+03, 1.0000e+00, 1.0000e+00])


In [29]:

a_tr = torch.ones( (60000, 784) )
a_tr.shape


torch.Size([60000, 784])

In [ ]:

(1)(1) + (-4)(3) + (5)(-5) = -36
(2)(1) + (3)(3)  + (-6)(-5) = 41



## Problem 37


In [32]:

x = torch.randn( 150, 4 )

x.shape


torch.Size([150, 4])

In [33]:

w = torch.randn( 4, 6 )

print( w.shape )


torch.Size([4, 6])


In [34]:

h1 = torch.matmul(  x, w  ) 


In [35]:

print( h1.shape ) 


torch.Size([150, 6])


In [39]:

a = np.array( [10, 20, 30] )
type(a)



numpy.ndarray

In [40]:

a_t = torch.from_numpy( a )
type( a_t  )


torch.Tensor


## Problem 57


In [44]:

a = torch.tensor ( [10] )

b = torch.tensor ( [32] )



In [45]:

def model( a, b ):
    return a + b



In [46]:

res = model(a, b)


In [47]:

res


tensor([42])

In [ ]:

[56]


In [ ]:

[ 45, 23, 43, 17]


In [ ]:

[[ 34, 45, 6],
 [ 34, 23, 3],
 [ 30, 15, 2]]



## Regression


In [54]:


class LinRegNet( nn.Module ):
    
    def __init__(self):
        super().__init__() 
        self.linear1 = nn.Linear(4, 1)

        ## x * w + b
    
    def forward(self, x):
        y_pred = self.linear1(x)
        return y_pred

    def generate(self):
        return




In [55]:

model = LinRegNet()




In [56]:

model


LinRegNet(
  (linear1): Linear(in_features=4, out_features=1, bias=True)
)

In [57]:

vec = torch.tensor( [3., 4., 5., 7. ]  )
vec


tensor([3., 4., 5., 7.])

In [58]:

y_pred = model( vec )
y_pred


tensor([1.3319], grad_fn=<ViewBackward0>)

In [ ]:

## 


In [ ]:

class Logistic_Regression_Net(nn.Module):
    
    def __init__( self ) :
        super().__init__ ()
        
        self. inear1 = nn.Linear(4 , 3)
        
        self.act1 = nn.Softmax(dim=1)

    def forward(self , x):
        x = self.linear1(x) 
        y_pred = self.act1( x )
        return y_pred


In [ ]:

[ 0.8, 0.7, 0.6]

[ 0.5, 0.3 , 0.2]


In [ ]:

[ 0, 1, 0]


In [ ]:

[-34, 567 ]


[ 0.1, 0.6 ] ]