In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [191]:

m = np.array(
        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]
)
m


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [192]:

 m < 5


array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [193]:
m > 11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [194]:

m == 14


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [195]:

np.equal(m, 13)


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [196]:

np.equal(m, 13)


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [197]:

  
np.sum(m < 12, axis=1)    
       
     


array([4, 4, 3, 0])

In [198]:

m[m < 8]


array([1, 2, 3, 4, 5, 6, 7])