In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [242]:

a = torch.tensor(  [[1, 2], [3, 4]]     )
print( a )

b = torch.tensor(  [[9, 8], [7, 6]]     )
print( b )

print( torch.multiply(a, b) )

print( torch.matmul(a, b) )


tensor([[1, 2],
        [3, 4]])
tensor([[9, 8],
        [7, 6]])
tensor([[ 9, 16],
        [21, 24]])
tensor([[23, 20],
        [55, 48]])
