In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [32]:

## slicing
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]] ) 

new_a = a[:2, :2]

new_a


array([[1, 2],
       [5, 6]])

In [33]:

new_a[0,0] = 42 
new_a


array([[42,  2],
       [ 5,  6]])

In [34]:

a


array([[42,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])