In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [127]:


m = np.array(
    [[1., 1., 1.],
     [1., 1., 1.],
     [1., 1., 1.]]
)

m

 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:

a = np.array(
    [0, 1, 2]
)

a


array([0, 1, 2])

In [129]:

m + a


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])


## Other


In [130]:

a = a[:, np.newaxis]

a


array([[0],
       [1],
       [2]])

In [131]:

m + a


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])


## Other


In [133]:

v1 = np.array( [1, 1, 1] )
v1


array([1, 1, 1])

In [134]:

v2 =  np.array( [[0],
                 [1],
                 [2]]
              )
v2


array([[0],
       [1],
       [2]])

In [135]:

v1 + v2


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [136]:

v1 * v2


array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [137]:

m


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [138]:

zz = v1 * v2


In [141]:

m * zz


array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])


## Other


In [171]:

v1 = np.array(  [1, 1, 1],
             
             )
v1

v1 = v1[ :, np.newaxis]

In [172]:

print( v1.shape )


(3, 1)


In [173]:

v2 = np.array( [0, 1, 2])
print( v2.shape )


(3,)


In [174]:

v2 = v2[np.newaxis, :]
print( v2.shape )


(1, 3)


In [175]:

v1 + v2


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [176]:

v1 * v2


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])