In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [62]:

x = np.array( [1, 2, 3, 4] )


x + 10
 

array([11, 12, 13, 14])

In [63]:

x - 10 


array([-9, -8, -7, -6])

In [64]:

x * 10


array([10, 20, 30, 40])

In [65]:

x / 2


array([0.5, 1. , 1.5, 2. ])

In [66]:

-x 


array([-1, -2, -3, -4])

In [67]:

x ** 3 


array([ 1,  8, 27, 64])

In [68]:

np.log(x)


array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [69]:

np.log2(x) 


array([0.       , 1.       , 1.5849625, 2.       ])

In [70]:

np.log10(x)


array([0.        , 0.30103   , 0.47712125, 0.60205999])