In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [60]:

a =   np.array(   [1, 2, 3, 4]  )
b =   np.array(   [5, 6, 7, 8]  )
c =   np.array(   [9, 10, 11]  )


print( np.vstack((a,b)) )

print( np.hstack((a,b)) )



[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
