In [1]:

import numpy as np
import matplotlib.pyplot as plt 
import torch


In [121]:

m = np.array(
                                  [[ 1,  2,  3,  4],
                                   [ 5, 6,  7,  8],
                                   [ 9, 10, 11, 12],
                                   [13, 14, 15, 16]]
)

m


 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:

m.sum() 


136

In [123]:

np.min(m, axis=0) 


array([1, 2, 3, 4])

In [124]:

np.min(m, axis=1) 


array([ 1,  5,  9, 13])

In [125]:

np.min(m, axis=-1)


array([ 1,  5,  9, 13])